config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :spaces, only: [:index, :new, :create, :update], param: :name

  namespace :api, constraints: { format: :json } do
    post :uploads, to: 'uploads#create'
    post :images, to: 'images#create'
  end

  namespace :api do
    scope :slack, controller: :slack, as: :slack do
      post :slash
    end
  end

  scope ':name' do
    resources :images, only: [:index] do
      collection do
        get :latest, to: 'images#latest', as: :latest
      end
    end

    resource :setting, controller: :space_settings, only: [:show, :update]

    resources :devices, only: [:create]

    post :permissions, to: 'permissions#create'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get ':name', to: 'spaces#show', as: :space_show

  get '/hello/revision', to: RevisionPlate::App.new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :space

  def self.generate_token
    SecureRandom.base64(24)
  end

  def self.create_with_token(params)
    create(params.merge(token: generate_token))
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :space
  has_many :image_metadata, class_name: 'ImageMetadata'

  after_create :recognize_image_if_needed

  RECOGNIZE_INTERVAL_IN_MINUTE = 10

  def self.bucket
    s3 = Aws::S3::Resource.new
    bucket = s3.bucket(ENV['LONELY_BUCKET_NAME'])
  end

  def s3_object
    self.class.bucket.object(key)
  end

  def key(format: :jpg)
    "#{s3_namespace}#{space.name}/#{timestamp.to_date.to_s}/#{timestamp.strftime('%Y-%m-%d %H:%M:%S')}.#{format}"
  end

  # returns public url
  def url
    s3_object.presigned_url(:get, expires_in: 7 * 24 * 60 * 60) # expires in a week
  end

  # by default, it's recognized every 10 minutes
  def should_be_recognized?
    return false if ENV['LONELY_DISABLE_WORKER']
    return true if Rails.env.development?

    !in_suspend_time? && timestamp.min % RECOGNIZE_INTERVAL_IN_MINUTE == 0
  end

  private
  def recognize_image_if_needed
    RecognitionWorker.perform_async(id) if should_be_recognized?
  end

  # most people sleeps between 0:00 and 6:59
  def in_suspend_time?
    0 <= timestamp.hour && timestamp.hour <= 6
  end

  def s3_namespace
    ENV['LONELY_BUCKET_NAMESPACE'] || ''
  end
end

app/models/image_metadata.rb
class ImageMetadata < ApplicationRecord
  belongs_to :image
  enum key: [:face]
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :space
end

app/models/slack_notification_log.rb
class SlackNotificationLog < ApplicationRecord
  belongs_to :space
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :images
  has_many :permissions
  has_many :permitted_users, through: :permissions, source: :user
  has_many :devices
  has_one :space_setting, dependent: :destroy
  has_many :slack_notification_logs, dependent: :destroy

  # private, public are reserved words. so use `visibility_` prefix.
  enum visibility: [:private, :public], _prefix: :visibility

  validates :name, presence: true, format: { with: /[a-z0-9_-]+/ }, length: { maximum: 20 }

  def self.create_with_user(params, user:)
    space = Space.create(params)

    if space.valid?
      space.permissions.create!(user: user)
    end

    space
  end

  def viewable_by?(user)
    visibility_public? || permitted_users.include?(user)
  end

  def editable_by?(user)
    permitted_users.include?(user)
  end

  def slack_slash_token
    Token.first_or_create!(token_type: :slack_slash, secret: Token.generate_secret, space: self)
  end
end

app/models/space_setting.rb
class SpaceSetting < ApplicationRecord
  belongs_to :space
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :space

  enum token_type: [:slack_slash]

  def self.generate_secret
    SecureRandom.urlsafe_base64(24)
  end
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEXP = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates :uid, presence: true
  validates :email, presence: true, format: { with: EMAIL_REGEXP }

  has_many :permissions
  has_many :spaces, through: :permissions
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_space
  before_action :require_editable

  def create
    device = Device.create_with_token(space: @space)

    respond_to do |format|
      if device.valid?
        format.html { redirect_to setting_path(@space.name) }
      else
        format.html { redirect_to setting_path(@space.name) }
      end
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_space
  before_action :require_viewable, only: [:index, :latest]

  PER_PAGE = 20

  def index
    step_in_minute = params[:step_in_minute]&.to_i || 1

    @images = @space.images
      .order(timestamp: :desc)
      .where('mod(extract(minute from timestamp)::integer, ?) = 0', step_in_minute)
      .page(params[:page]&.to_i || 1)
      .per(params[:per_page]&.to_i || PER_PAGE)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def latest
    @image = @space.images.order(timestamp: :desc).first!

    respond_to do |format|
      format.html do
        redirect_to @image.url, status: :found
      end
      format.json
    end
  end

  private
  def set_space
    @space = Space.find_by!(name: params[:name])
  end
end

app/controllers/space_settings_controller.rb
class SpaceSettingsController < ApplicationController
  before_action :set_space
  before_action :require_user
  before_action :require_editable

  def show
    @devices = @space.devices
  end

  def update
    setting = @space.space_setting || @space.create_space_setting!

    setting.update!(setting_params)
  end

  private
  def setting_params
    params.require(:space_setting).permit(:slack_incoming_webhook_url)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :update, :settings]
  before_action :require_user, only: [:create, :settings, :index]
  before_action :require_viewable, only: [:show]
  before_action :require_editable, only: [:update, :settings]

  def index
    @spaces = current_user.permissions.includes(:space).map(&:space)
  end

  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.create_with_user(space_params, user: current_user)

    respond_to do |format|
      if @space.valid?
        format.html { redirect_to space_show_path(@space.name), notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @space.update(update_params)
        format.html { redirect_to setting_path(@space.name) }
      else
        format.html { redirect_to setting_path(@space.name) }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name)
    end

    def update_params
      params.require(:space).permit(:visibility)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  before_action :redirect_if_logined

  def index
  end

  private
  def redirect_if_logined
    if current_user
      permissions = current_user.permissions.includes(:space)
      if permissions.size == 1
        redirect_to space_show_path(permissions.first.space.name)
      else
        redirect_to spaces_path
      end
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    space = Space.find_by!(name: params[:name])

    timestamp = Time.now
    obj = Image.new(space: space, timestamp: timestamp).s3_object
    @presigned_url = obj.presigned_url(:put, content_type: 'image/jpeg')

    render json: {
      timestamp: timestamp.to_i,
      presigned_url: @presigned_url
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/space_settings/show.haml
- content_for(:title, @space.name)
= render 'shared/space_nav'

.container
  %main.setting
    %section
      %h2.title= t('space_setting_members_title')
      %p.description= t('space_setting_members_description')
      %table.table
        %tbody
          - @space.permitted_users.each do |permitted_user|
            %tr
              %td
                = permitted_user.email

      = form_tag permissions_path, method: :post do |f|
        = label_tag 'Email'
        = email_field_tag :email, nil, placeholder: 'email', class: 'form-control input'
        = submit_tag t('space_setting_members_submit'), class: 'btn btn-primary btn-lg btn-block'

    %section
      %h2 Visibility

      = form_for @space, url: space_path(@space.name), method: :put do |f|
        .form-check
          %label.form-check-label
            = f.radio_button :visibility, :private, checked: @space.visibility == 'private'
            Private (default) - Only members can see this space and edit the settings.

        .form-check
          %label.form-check-label
            = f.radio_button :visibility, :public, checked: @space.visibility == 'public'
            Public - Anyone can see this space. Only members can edit the settings.

        = f.submit 'Update', class: 'btn btn-primary btn-lg btn-block'

    %section
      %h2.title Slack notification

      - setting = @space.space_setting || @space.build_space_setting
      = form_for setting, url: setting_path(@space.name), method: :put do |f|
        = f.label 'incoming webhook url'
        = f.text_field :slack_incoming_webhook_url, class: 'form-control input'

        = f.submit 'Update', class: 'btn btn-primary btn-lg btn-block'

    %section
      %h2.title Slack slash command
      %p
        Paste this URL at
        = link_to 'Slash Commands settings', 'https://slack.com/apps/A0F82E8CA-slash-commands?page=1', target: '_blank'

      %pre
        = api_slack_slash_url(secret: @space.slack_slash_token.secret)

    %section
      %h2.title Devices
      %p You can create new device and get a device token to upload photos.

      - if @devices.present?
        %table.table
          %thead
            %tr
              %th id
              %th token

          %tbody
            - @devices.each do |device|
              %tr
                %td
                  = device.id
                %td
                  = device.token
      - else
        %p no device

      = form_for Device.new, url: devices_path(@space.name) do |f|
        = f.submit 'Create new device', class: 'btn btn-primary btn-lg btn-block'