config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :spaces, only: [:index, :new, :create, :update], param: :name

  namespace :api, constraints: { format: :json } do
    post :uploads, to: 'uploads#create'
    post :images, to: 'images#create'
  end

  namespace :api do
    scope :slack, controller: :slack, as: :slack do
      post :slash
    end
  end

  scope ':name' do
    resources :images, only: [:index] do
      collection do
        get :latest, to: 'images#latest', as: :latest
      end
    end

    resource :setting, controller: :space_settings, only: [:show, :update]

    resources :devices, only: [:create]

    post :permissions, to: 'permissions#create'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get ':name', to: 'spaces#show', as: :space_show

  get '/hello/revision', to: RevisionPlate::App.new
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :images
  has_many :permissions
  has_many :permitted_users, through: :permissions, source: :user
  has_many :devices
  has_one :space_setting, dependent: :destroy
  has_many :slack_notification_logs, dependent: :destroy

  # private, public are reserved words. so use `visibility_` prefix.
  enum visibility: [:private, :public], _prefix: :visibility

  validates :name, presence: true, format: { with: /[a-z0-9_-]+/ }, length: { maximum: 20 }

  def self.create_with_user(params, user:)
    space = Space.create(params)

    if space.valid?
      space.permissions.create!(user: user)
    end

    space
  end

  def viewable_by?(user)
    visibility_public? || permitted_users.include?(user)
  end

  def editable_by?(user)
    permitted_users.include?(user)
  end

  def slack_slash_token
    Token.first_or_create!(token_type: :slack_slash, secret: Token.generate_secret, space: self)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :update, :settings]
  before_action :require_user, only: [:create, :settings, :index]
  before_action :require_viewable, only: [:show]
  before_action :require_editable, only: [:update, :settings]

  def index
    @spaces = current_user.permissions.includes(:space).map(&:space)
  end

  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.create_with_user(space_params, user: current_user)

    respond_to do |format|
      if @space.valid?
        format.html { redirect_to space_show_path(@space.name), notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @space.update(update_params)
        format.html { redirect_to setting_path(@space.name) }
      else
        format.html { redirect_to setting_path(@space.name) }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name)
    end

    def update_params
      params.require(:space).permit(:visibility)
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.haml
= form_with(model: space, local: true) do |form|
  - if space.errors.any?
    #error_explanation
      %ul
        - space.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :name
    = form.text_field :name, id: :space_name, class: 'form-control'

  .actions
    = form.submit class: 'btn btn-primary btn-lg btn-block'

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.haml
%p#notice= notice

.container
  %h1 Spaces

  %ul
    - @spaces.each do |space|
      %li
        = link_to space.name, space_show_path(space.name)

  = link_to 'New Space', new_space_path, class: 'btn btn-primary'

app/views/spaces/new.haml
.container
  %h1 New Space

  = render 'form', space: @space

app/views/spaces/show.haml
- content_for(:title, @space.name)

= render 'shared/space_nav'

.container
  #react-root